default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: postgres
  password: <%= ENV['WOODMAN_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: woodman_development

test:
  <<: *default
  database: woodman_test

production:
  <<: *default
  database: woodman_production
  username: postgres
  password: <%= ENV['WOODMAN_DATABASE_PASSWORD'] %>